### ISSUE TITLE
iPhone - Contact / Newsletter submission message - Please apply same design as desktop/tablet. 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Wednesday-Night-Wine#18]

**Comment by ccmorris** [comment]
It is exactly the same design. Am I missing something? Can you take a screenshot?

**Comment by tgascoigne14** [comment]
![img_3301](https://cloud.githubusercontent.com/assets/8631079/17944235/e0097466-6a0c-11e6-8306-46aaa2a10393.png)
![img_3302](https://cloud.githubusercontent.com/assets/8631079/17944234/e006b6d6-6a0c-11e6-8302-0c82f4bad609.png)

**Comment by tgascoigne14** [comment]
Thank you + Name + for getting in contact should be centred and missing the mail icon.

**Comment by ccmorris** [comment]
clear cache
refresh

**Comment by tgascoigne14** [comment]
Spot on mate
